// <auto-generated />
using System;
using CrmService.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace CrmService.Migrations
{
    [DbContext(typeof(CrmDbContext))]
    [Migration("20260308010000_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63)
                .UseIdentityByDefaultColumns();

            modelBuilder.Entity("CrmService.Models.CampagneMarketing", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("integer");

                NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                b.Property<decimal>("Budget")
                    .HasColumnType("numeric(18,2)");

                b.Property<DateTime>("DateDebut")
                    .HasColumnType("timestamp with time zone");

                b.Property<DateTime>("DateFin")
                    .HasColumnType("timestamp with time zone");

                b.Property<string>("Nom")
                    .IsRequired()
                    .HasMaxLength(200)
                    .HasColumnType("character varying(200)");

                b.HasKey("Id");

                b.ToTable("campagnes_marketing", (string)null);
            });

            modelBuilder.Entity("CrmService.Models.Lead", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("integer");

                NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                b.Property<int?>("CampagneId")
                    .HasColumnType("integer");

                b.Property<DateTime>("DateCreation")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("timestamp with time zone")
                    .HasDefaultValueSql("NOW()");

                b.Property<int>("Score")
                    .HasColumnType("integer");

                b.Property<string>("Source")
                    .IsRequired()
                    .HasMaxLength(100)
                    .HasColumnType("character varying(100)");

                b.Property<int>("Statut")
                    .HasColumnType("integer");

                b.Property<int?>("UtilisateurId")
                    .HasColumnType("integer");

                b.HasKey("Id");

                b.HasIndex("CampagneId");

                b.ToTable("leads", (string)null);
            });

            modelBuilder.Entity("CrmService.Models.Opportunite", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("integer");

                NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                b.Property<DateTime?>("DateCloture")
                    .HasColumnType("timestamp with time zone");

                b.Property<int>("LeadId")
                    .HasColumnType("integer");

                b.Property<int>("Statut")
                    .HasColumnType("integer");

                b.Property<string>("Titre")
                    .IsRequired()
                    .HasMaxLength(200)
                    .HasColumnType("character varying(200)");

                b.Property<decimal>("Valeur")
                    .HasColumnType("numeric(18,2)");

                b.HasKey("Id");

                b.HasIndex("LeadId")
                    .IsUnique();

                b.ToTable("opportunites", (string)null);
            });

            modelBuilder.Entity("CrmService.Models.Lead", b =>
            {
                b.HasOne("CrmService.Models.CampagneMarketing", "Campagne")
                    .WithMany("Leads")
                    .HasForeignKey("CampagneId")
                    .OnDelete(DeleteBehavior.SetNull);

                b.Navigation("Campagne");
            });

            modelBuilder.Entity("CrmService.Models.Opportunite", b =>
            {
                b.HasOne("CrmService.Models.Lead", "Lead")
                    .WithOne("Opportunite")
                    .HasForeignKey("CrmService.Models.Opportunite", "LeadId")
                    .OnDelete(DeleteBehavior.Restrict)
                    .IsRequired();

                b.Navigation("Lead");
            });

            modelBuilder.Entity("CrmService.Models.CampagneMarketing", b =>
            {
                b.Navigation("Leads");
            });

            modelBuilder.Entity("CrmService.Models.Lead", b =>
            {
                b.Navigation("Opportunite");
            });
#pragma warning restore 612, 618
        }
    }
}
