CREATE TABLE factures (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    numero VARCHAR(50) UNIQUE NOT NULL,
    montant_ht NUMERIC(19,2) NOT NULL DEFAULT 0.00,
    taux_tva NUMERIC(5,4) NOT NULL DEFAULT 0.2000,
    montant_tva NUMERIC(19,2) NOT NULL DEFAULT 0.00,
    montant_ttc NUMERIC(19,2) NOT NULL DEFAULT 0.00,
    montant_paye NUMERIC(19,2) NOT NULL DEFAULT 0.00,
    reste_a_payer NUMERIC(19,2) NOT NULL DEFAULT 0.00,
    statut VARCHAR(30) NOT NULL,
    date_creation TIMESTAMP WITH TIME ZONE NOT NULL,
    date_mise_a_jour TIMESTAMP WITH TIME ZONE NOT NULL
);

CREATE INDEX idx_factures_statut ON factures(statut);
CREATE INDEX idx_factures_numero ON factures(numero);

CREATE TABLE lignes_facture (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    facture_id BIGINT NOT NULL,
    produit VARCHAR(255) NOT NULL,
    quantite INTEGER NOT NULL CHECK (quantite > 0),
    prix_unitaire NUMERIC(19,2) NOT NULL CHECK (prix_unitaire > 0),
    total_ligne NUMERIC(19,2) NOT NULL DEFAULT 0.00,
    CONSTRAINT fk_ligne_facture FOREIGN KEY (facture_id) REFERENCES factures(id) ON DELETE CASCADE
);

CREATE INDEX idx_lignes_facture_facture_id ON lignes_facture(facture_id);
