CREATE TABLE journal_transactions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    date_ecriture TIMESTAMP WITH TIME ZONE NOT NULL,
    compte_debit VARCHAR(20) NOT NULL,
    compte_credit VARCHAR(20) NOT NULL,
    debit NUMERIC(19,2) NOT NULL CHECK (debit >= 0),
    credit NUMERIC(19,2) NOT NULL CHECK (credit >= 0),
    reference_type VARCHAR(30) NOT NULL,
    reference_id BIGINT NOT NULL,
    description VARCHAR(500),
    CONSTRAINT ck_journal_equilibre CHECK (debit = credit)
);

CREATE INDEX idx_journal_compte_debit ON journal_transactions(compte_debit);
CREATE INDEX idx_journal_compte_credit ON journal_transactions(compte_credit);
CREATE INDEX idx_journal_reference ON journal_transactions(reference_type, reference_id);
