CREATE TABLE paiements (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    facture_id BIGINT NOT NULL,
    date_paiement TIMESTAMP WITH TIME ZONE NOT NULL,
    montant NUMERIC(19,2) NOT NULL CHECK (montant > 0),
    mode_paiement VARCHAR(30) NOT NULL,
    reference_transaction VARCHAR(120) NOT NULL UNIQUE,
    statut VARCHAR(30) NOT NULL,
    date_creation TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT fk_paiements_facture FOREIGN KEY (facture_id) REFERENCES factures(id) ON DELETE RESTRICT
);

CREATE INDEX idx_paiements_facture_id ON paiements(facture_id);
CREATE INDEX idx_paiements_statut ON paiements(statut);
